spring:
    profiles:
        active: prod
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://fquick-db-master.nm.flipkart.com:3306/fquick_timer?useUnicode=true&characterEncoding=utf8
        databaseName:
        serverName:
        username: fquick_timer_rw
        password: aypbvl
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
        properties:
                    hibernate.cache.use_second_level_cache: false
                    hibernate.cache.use_query_cache: false
                    hibernate.generate_statistics: true
                    org.hibernate.envers.audit_table_suffix: _history

http:
    cache:
        timeToLiveInDays: 31

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 256M

health:
  rotationConfig:
    persistentFilePath: /var/lib/fquick-timer/public/rotation_status.txt

endpoints.health.sensitive: false

requestLog:
    timeZone: IST
    logFilename: /var/log/flipkart/fquick-timer/access-yyyy_mm_dd.log
    maxHistory: 6

restBusConfig:
  restBusUrl: http://varadhi.nm.flipkart.com
  authLoginUrl: https://flo-rubycas-server.nm.flipkart.com/login
  authLoginUser: fq_spider
  authLoginPassword: Y6XoQTrN
  authEnabled: true
  restEnvName: production
  saveRequestBody: false
