spring:
    profiles:
        active: dev
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/fquick_timer?useUnicode=true&characterEncoding=utf8
        databaseName:
        serverName:
        username: root
        password:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
        properties:
                    hibernate.cache.use_second_level_cache: false
                    hibernate.cache.use_query_cache: false
                    hibernate.generate_statistics: true
                    org.hibernate.envers.audit_table_suffix: _history

http:
    cache:
        timeToLiveInDays: 31

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 256M

health:
  rotationConfig:
    persistentFilePath: /Users/Documents/work/fquick-timer/public/rotation_status.txt

endpoints.health.sensitive: false

requestLog:
    timeZone: IST
    logFilename: ./log/access-yyyy_mm_dd.log
    maxHistory: 6

restBusConfig:
  restBusUrl: http://varadhi.stage.ch.flipkart.com
  authLoginUrl: https://flo-rubycas-server.stage.ch.flipkart.com/login
  authLoginUser: sc_jarvis_b2c
  authLoginPassword: Y6XoQTrN
  authEnabled: true
  restEnvName: local
  saveRequestBody: false

